swagger: "2.0"
info:
  description: "Service responsible for handling videos keywords."
  version: "1.0.0"
  title: "Keywords Microservice"
host: "keywordsbackend.azurewebsites.net"
basePath: "/"
tags:
  - name: "keyword"
    description: "Everything about video keywords"
schemes:
  - "http"
paths:
  /keywords/:
    post:
      tags:
        - "keyword"
      summary: "Get paginated keywords for a video"
      description: "Get paginated keywords for a video"
      operationId: "GetAllKeywordsByVideoId"
      parameters:
        - name: PaginatedKeywordsRequest
          in: body
          required: true
          description: Contains pagination details
          schema:
            $ref: "#/definitions/PaginatedKeywordsRequest"
      responses:
        200:
          description: Returns all keywords paginated
          schema:
            $ref: "#/definitions/PaginatedKeywordsResponse"
        400:
          description: Bad request
        404:
          description: Video not found
  /keyword/keywordId/{keywordId}:
    get:
      tags:
        - "keyword"
      summary: "Get a keyword by its id"
      description: "Get a keyword by its id"
      operationId: "GetKeyword"
      parameters:
        - name: keywordId
          in: path
          description: Keyword Id to get the keyword entity for
          required: true
          type: string
          format: guid
      responses:
        200:
          description: Keyword found
          schema:
            $ref: "#/definitions/Keyword"
        404:
          description: Keyword not found
    put:
      tags:
        - "keyword"
      summary: "Publish a keyword using its id"
      description: "Publish keyboard using its id"
      operationId: PublishKeyword
      parameters:
        - name: keywordId
          in: path
          description: Keyword Id
          required: true
          type: string
          format: guid
        - name: toBePublished
          in: query
          description: Bool to state whether will be published or not
          required: false
          type: boolean
      responses:
        200:
          description: Keyword published
          schema:
            $ref: "#/definitions/Keyword"
        404:
          description: Keyword not found
  /indexer/{videoId}:
    get:
      tags:
        - "indexer"
      summary: "Get a keyword list of the indexed video"
      description: "Get a keyword list of the indexed video"
      operationId: "GetIndexerResponse"
      parameters:
        - name: videoId
          in: path
          description: Video Id to get the video ocr for
          required: true
          type: string
          format: guid
      responses:
        200:
          description: Ocr video found
          schema:
            $ref: "#/definitions/IndexerResponse"
        404:
          description: Not found
    post:
      tags:
        - "indexer"
      summary: "Index a video"
      description: "Index a video"
      operationId: "IndexVideo"
      parameters:
        - name: videoId
          in: path
          description: Video id to index
          required: true
          type: string
          format: guid
        - name: url
          in: query
          description: Video url to index
          required: true
          type: string
      responses:
        200:
          description: Video index started
        404:
          description: Not found
definitions:
  Keyword:
    type: object
    properties:
      Id:
        type: string
        format: guid
        description: Id of the keyword
      Content:
        type: string
        description: Keyword's content can be a word or a phrase
      VideoId:
        type: string
        format: guid
        description: Id of the video that the keyword belongs to
      IsPublished:
        type: boolean
        description: States if the Keyword is available for users
      Language:
        type: string
        description: The language the keyword belongs to
      AudioLink:
        type: string
        description: Link to the keyword's audio

  PaginatedKeywordsRequest:
    type: object
    properties:
      VideoId:
        type: string
        format: guid
        description: Video Id to get the keywords for
      Size:
        type: integer
        description: Size of the page
      Page:
        type: integer
        description: Page number
  PaginatedKeywordsResponse:
    type: object
    properties:
      Keywords:
        type: array
        description: List of videos
        items:
          $ref: '#/definitions/Keyword'
      SizeRequested:
        type: integer
        description: Size of the page that was requested
      TotalAmount:
        type: integer
        description: Total number of keywords retrieved
      CurrentPage:
        type: integer
        description: Current page
      TotalAmountOfPages:
        type: integer
        description: Total number of pages based on the specified size
  
  IndexerResponse:
    type: object
    properties:
      state:
        type: string
        enum: [Indexing,
               ExtractingKeyPhrases,
               Failed,
               Succeeded]
      processingProgress:
        type: string
      keywords:
        type: array
        items:
          $ref: '#/definitions/Keyword'
  